apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
  labels:
    app: yolo5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
        labels:
          app: yolo5
    spec:
      containers:
      - name: server
        image: ehabo215/yolo5:latest
        env:
          - name: YOLO%
            value: http://netflix-catalog-service:8080
          - name: REDIS_URL
            value: redis-service:6379
---
apiVersion: v1
kind: Service
metadata:
  name: yolo5-service
spec:
  selector:
    app: yolo5
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000